<?php
declare(strict_types=1);

final class MigrationRunner
{
    private UpdateRepository $repo;
    public function __construct(UpdateRepository $repo){$this->repo=$repo;}

    public function applyNext(array $job,array $manifest,string $stagingRoot,UpdateLogger $logger): array
    {
        $uuid=(string)$job['job_uuid'];$context=$this->repo->context($job);$migrations=array_values($manifest['migrations']??[]);$index=(int)($context['migration_index']??0);if($index>=count($migrations)){$context['migrations_complete']=true;return $this->repo->saveContext($uuid,$context);} $migration=$migrations[$index];$id=(string)$migration['id'];$checksum=(string)$migration['checksum'];$path=(string)$migration['path'];$existing=$this->repo->migration($id);if($existing&&($existing['status']??'')==='applied'&&hash_equals((string)$existing['checksum'],$checksum)){$logger->info('migrate','MIGRATION_ALREADY_APPLIED','Migration already applied: '.$id);$context['migration_index']=$index+1;$context['applied_migrations']=$context['applied_migrations']??[];if(!in_array($id,$context['applied_migrations'],true)){$context['applied_migrations'][]=$id;}return $this->repo->saveContext($uuid,$context);}
        $full=$stagingRoot.'/'.$path;if(!is_file($full)||!hash_equals(strtolower($checksum),strtolower((string)hash_file('sha256',$full)))){throw new UpdateException('MIGRATION_FILE_INVALID','Migration file checksum validation failed.',400);} $context['migration_in_progress']=$id;$this->repo->saveContext($uuid,$context);$this->repo->startMigration($id,(string)$job['target_version'],$checksum);$logger->info('migrate','MIGRATION_START','Applying migration '.$id.'.');$started=microtime(true);
        try{$sql=(string)file_get_contents($full);$statements=UpdateSchema::splitSql($sql);if(!$statements){throw new UpdateException('MIGRATION_EMPTY','Migration contains no executable SQL.',400);}foreach($statements as $statement){$this->repo->db()->exec($statement);} $ms=(int)round((microtime(true)-$started)*1000);$this->repo->finishMigration($id,$ms);$context['migration_index']=$index+1;$context['applied_migrations']=$context['applied_migrations']??[];if(!in_array($id,$context['applied_migrations'],true)){$context['applied_migrations'][]=$id;}unset($context['migration_in_progress']);$logger->success('migrate','MIGRATION_COMPLETE','Migration completed: '.$id.'.',['execution_ms'=>$ms]);return $this->repo->saveContext($uuid,$context);}catch(Throwable $e){$this->repo->failMigration($id,$e->getMessage());throw $e;}
    }

    public function rollbackNext(array $job,array $manifest,string $stagingRoot,UpdateLogger $logger): array
    {
        $uuid=(string)$job['job_uuid'];$context=$this->repo->context($job);if(!isset($context['rollback_migration_ids'])){$ids=array_values($context['applied_migrations']??[]);if(!empty($context['migration_in_progress'])&&!in_array($context['migration_in_progress'],$ids,true)){$ids[]=$context['migration_in_progress'];}$context['rollback_migration_ids']=array_reverse($ids);$context['rollback_migration_index']=0;$job=$this->repo->saveContext($uuid,$context);} $context=$this->repo->context($job);$ids=$context['rollback_migration_ids']??[];$idx=(int)($context['rollback_migration_index']??0);if($idx>=count($ids)){$context['rollback_migrations_complete']=true;return $this->repo->saveContext($uuid,$context);} $id=(string)$ids[$idx];$meta=null;foreach($manifest['migrations']??[] as $candidate){if(($candidate['id']??'')===$id){$meta=$candidate;break;}} if(!$meta){$context['rollback_migration_index']=$idx+1;return $this->repo->saveContext($uuid,$context);} $rollbackPath=(string)($meta['rollback_path']??'');if($rollbackPath===''){$logger->warning('rollback','MIGRATION_ADDITIVE_RETAINED','Additive migration has no destructive rollback and will remain in place: '.$id.'.');$context['rollback_migration_index']=$idx+1;return $this->repo->saveContext($uuid,$context);} $full=$stagingRoot.'/'.$rollbackPath;$expected=(string)($meta['rollback_checksum']??'');if(!is_file($full)||!hash_equals(strtolower($expected),strtolower((string)hash_file('sha256',$full)))){throw new UpdateException('ROLLBACK_MIGRATION_INVALID','Rollback migration checksum validation failed.',500);} $logger->warning('rollback','MIGRATION_ROLLBACK_START','Rolling back migration '.$id.'.');foreach(UpdateSchema::splitSql((string)file_get_contents($full)) as $statement){$this->repo->db()->exec($statement);} $this->repo->removeMigrationRecord($id);$logger->success('rollback','MIGRATION_ROLLBACK_COMPLETE','Migration rollback completed: '.$id.'.');$context['rollback_migration_index']=$idx+1;return $this->repo->saveContext($uuid,$context);
    }
}
