<?php
declare(strict_types=1);
$root=dirname(__DIR__);
function up_ok($v,string $m):void{if(!$v){fwrite(STDERR,"FAIL: {$m}\n");exit(1);}}
$required=[
 'admin/updates.php','admin/ajax/update-check.php','admin/ajax/update-preflight.php','admin/ajax/update-start.php','admin/ajax/update-step.php','admin/ajax/update-status.php','admin/ajax/update-events.php','admin/ajax/update-diagnostics.php','admin/ajax/update-rollback.php',
 'includes/updater/UpdateService.php','includes/updater/UpdateRepository.php','includes/updater/ManifestVerifier.php','includes/updater/ArchiveValidator.php','includes/updater/BackupService.php','includes/updater/MigrationRunner.php','includes/updater/FileInstaller.php','includes/updater/RollbackService.php','includes/updater/UpdateLock.php','includes/updater/update-signing-public.pem',
 'migration-v5.3.0-updater.sql','update/release-spec.json','scripts/build-update-manifest.py','scripts/verify-release-update.php','admin/assets/css/licora-updater.css','admin/assets/js/licora-updater.js'
];
foreach($required as $rel){up_ok(is_file($root.'/'.$rel),'missing updater file '.$rel);}
$service=(string)file_get_contents($root.'/includes/updater/UpdateService.php');foreach(['fetch_manifest','preflight','backup_database','rollback_migrations','AUTO_ROLLBACK_SCHEDULED','previewPreflight','UpdateLock::acquire','PACKAGE_SIZE_MISMATCH','withCoordinatorLock'] as $marker){up_ok(strpos($service,$marker)!==false,'missing state-machine marker '.$marker);}
$verifier=(string)file_get_contents($root.'/includes/updater/ManifestVerifier.php');foreach(['openssl_verify','UPDATE_SIGNATURE_INVALID','UPDATE_PROTECTED_PATH','UPDATE_SOURCE_VERSION_UNSUPPORTED','upgrade_from','delete_files','rollback_checksum'] as $marker){up_ok(strpos($verifier,$marker)!==false,'missing manifest-security marker '.$marker);}
$http=(string)file_get_contents($root.'/includes/updater/HttpClient.php');up_ok(strpos($http,"'https'")!==false,'HTTPS-only transport marker missing');up_ok(strpos($http,'.githubusercontent.com')!==false,'trusted GitHub redirect boundary missing');up_ok(strpos($http,'CURLOPT_FOLLOWLOCATION=>false')!==false,'cURL redirects must be manually validated before fetching');up_ok(strpos($http,'resolveRedirect')!==false,'validated redirect resolver missing');up_ok(strpos($http,'streamDownload')!==false,'stream fallback must download in bounded chunks rather than buffer the full package');
$releaseClient=(string)file_get_contents($root.'/includes/updater/ReleaseClient.php');up_ok(strpos($releaseClient,"OFFICIAL_REPOSITORY = 'vibtools/Licora'")!==false,'updater repository must be pinned to the official Licora repository');
$all='';foreach(glob($root.'/includes/updater/*.php') as $f){$all.=(string)file_get_contents($f);}foreach(['shell_exec(','system(','passthru(','proc_open('] as $bad){up_ok(strpos($all,$bad)===false,'updater core must not depend on shell execution: '.$bad);}
$ui=(string)file_get_contents($root.'/admin/updates.php');foreach(['Copy Logs','Download Diagnostics','Pin to bottom','update-log-search','update-log-filter','Closing this window does not cancel'] as $marker){up_ok(strpos($ui,$marker)!==false,'VibTools live-log contract missing '.$marker);}up_ok(strpos($ui,'AI Diagnostics')===false,'demo-only AI Diagnostics must not ship as a fake updater feature');
$release=(string)file_get_contents($root.'/.github/workflows/release.yml');foreach(['LICORA_UPDATE_SIGNING_PRIVATE_KEY','licora-update-manifest.json','licora-update-manifest.sig','openssl dgst -sha256 -sign','scripts/verify-release-update.php','tests/updater_db_integration.php'] as $marker){up_ok(strpos($release,$marker)!==false,'release signing/gate missing '.$marker);}
$lock=(string)file_get_contents($root.'/includes/updater/UpdateLock.php');foreach(['recoverOrphaned','writeAtomic','recovered corrupt critical lock metadata'] as $marker){up_ok(strpos($lock,$marker)!==false,'critical lock recovery marker missing '.$marker);}
$schema=(string)file_get_contents($root.'/includes/updater/UpdateSchema.php');up_ok(strpos($schema,'UPDATER_BASE_SCHEMA_MISSING')!==false,'controlled updater base-schema prerequisite guard missing');
$builder=(string)file_get_contents($root.'/scripts/build-update-manifest.py');up_ok(strpos($builder,'upgrade_from')!==false,'signed source-version compatibility contract missing from manifest builder');

$archive=(string)file_get_contents($root.'/includes/updater/ArchiveValidator.php');foreach(['UPDATE_ZIP_SPECIAL_FILE','UPDATE_ZIP_SYMLINK','case-colliding path'] as $marker){up_ok(strpos($archive,$marker)!==false,'archive hardening marker missing '.$marker);}
up_ok(strpos($builder,'protected package path')!==false,'manifest builder must reject protected packaged paths');up_ok(strpos($builder,'delete_files overlaps packaged source')!==false,'manifest builder must reject deletion/package overlap');up_ok(strpos($builder,'duplicate migration id')!==false,'manifest builder must reject duplicate migration IDs');
$dom=(string)file_get_contents($root.'/admin/assets/js/licora-updater.js');up_ok(strpos($dom,"el('licora-update-log-title')")!==false,'updater live-log title DOM contract must match HTML');up_ok(strpos($dom,"el('update-log-title')")===false,'broken updater live-log title selector must be absent');up_ok(strpos($dom,'jobIsActive')!==false,'terminal jobs must not be treated as active updater jobs');up_ok(strpos($dom,'confirm(')===false,'native browser confirm must not bypass the Licora UI component system');
$spec=(string)file_get_contents($root.'/update/release-spec.json');up_ok(strpos($spec,'upgrade_from')!==false,'release spec source-version contract missing');
$boot=(string)file_get_contents($root.'/admin/ajax/update-bootstrap.php');up_ok(strpos($boot,"\$method!=='POST'")!==false,'mutation endpoints must enforce POST');

$logger=(string)file_get_contents($root.'/includes/updater/UpdateLogger.php');up_ok(strpos($logger,'Update event telemetry must never')!==false,'updater event logging must be non-fatal to the state machine');
$backup=(string)file_get_contents($root.'/includes/updater/BackupService.php');foreach(['source_backup_modes','source_backup_hashes','SOURCE_BACKUP_HASH_FAILED','SHOW TRIGGERS','SHOW CREATE TRIGGER','DATABASE_BACKUP_TRIGGERS'] as $marker){up_ok(strpos($backup,$marker)!==false,'backup safety marker missing '.$marker);}
$rollback=(string)file_get_contents($root.'/includes/updater/RollbackService.php');up_ok(strpos($rollback,'source_backup_modes')!==false,'source rollback must restore original file permissions');up_ok(strpos($rollback,'ROLLBACK_BACKUP_INVALID')!==false,'source rollback must verify retained backup content');
$installer=(string)file_get_contents($root.'/includes/updater/FileInstaller.php');up_ok(strpos($installer,'fileperms($target)')!==false,'file installer must preserve existing source permissions');
foreach(['forever-running job','stepHandle=null','lockAcquired=false','chunked dump internally inconsistent','updater_auto_check=0 must not initiate'] as $marker){up_ok(strpos($service,$marker)!==false,'updater recovery hardening marker missing '.$marker);}

$gitignore=(string)file_get_contents($root.'/.gitignore');up_ok(strpos($gitignore,'includes/.licora-updater/')!==false,'runtime updater storage must be ignored');up_ok(strpos($gitignore,'update-signing-private.pem')!==false,'update private key must be ignored');
echo "Updater static checks passed.\n";
