<?php
declare(strict_types=1);
$root=dirname(__DIR__);require_once $root.'/includes/updater/UpdateException.php';require_once $root.'/includes/updater/ManifestVerifier.php';
function um_ok($v,string $m):void{if(!$v){fwrite(STDERR,"FAIL: {$m}\n");exit(1);}}
$key=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA]);um_ok($key!==false,'ephemeral RSA key generation');openssl_pkey_export($key,$private);$details=openssl_pkey_get_details($key);$public=$details['key']??'';um_ok($public!=='','ephemeral public key');$tmp=tempnam(sys_get_temp_dir(),'licora-updater-pub-');file_put_contents($tmp,$public);
$manifest=['protocol_version'=>1,'application'=>'Licora','version'=>'5.3.1','tag'=>'v5.3.1','commit'=>str_repeat('a',40),'channel'=>'stable','minimum_updater'=>'5.3.0','minimum_php'=>'8.0','package'=>['name'=>'Licora-5.3.1.zip','sha256'=>str_repeat('b',64),'size'=>1234],'migrations'=>[],'delete_files'=>[],'files'=>['README.md'=>str_repeat('c',64)]];$json=json_encode($manifest,JSON_UNESCAPED_SLASHES);openssl_sign($json,$sig,$private,OPENSSL_ALGO_SHA256);$v=new ManifestVerifier($tmp);$verified=$v->verify($json,$sig,'5.3.1');um_ok($verified['version']==='5.3.1','valid signed manifest accepted');
$failed=false;try{$v->verify($json." ",$sig,'5.3.1');}catch(UpdateException $e){$failed=$e->errorCode()==='UPDATE_SIGNATURE_INVALID';}um_ok($failed,'tampered manifest rejected');
$manifest['files']['includes/config.local.php']=str_repeat('d',64);$bad=json_encode($manifest,JSON_UNESCAPED_SLASHES);openssl_sign($bad,$badSig,$private,OPENSSL_ALGO_SHA256);$failed=false;try{$v->verify($bad,$badSig,'5.3.1');}catch(UpdateException $e){$failed=$e->errorCode()==='UPDATE_PROTECTED_PATH';}um_ok($failed,'protected deployment path rejected');

$manifest=['protocol_version'=>1,'application'=>'Licora','version'=>'5.3.1','tag'=>'v5.3.1','commit'=>str_repeat('a',40),'channel'=>'stable','minimum_updater'=>'5.3.0','minimum_php'=>'8.0','package'=>['name'=>'Licora-5.3.1.zip','sha256'=>str_repeat('b',64),'size'=>0],'migrations'=>[],'delete_files'=>[],'files'=>['README.md'=>str_repeat('c',64)]];
$bad=json_encode($manifest,JSON_UNESCAPED_SLASHES);openssl_sign($bad,$badSig,$private,OPENSSL_ALGO_SHA256);$failed=false;try{$v->verify($bad,$badSig,'5.3.1');}catch(UpdateException $e){$failed=$e->errorCode()==='UPDATE_MANIFEST_INVALID';}um_ok($failed,'non-positive package size rejected');
$manifest['package']['size']=1234;$manifest['delete_files']=['README.md'];$bad=json_encode($manifest,JSON_UNESCAPED_SLASHES);openssl_sign($bad,$badSig,$private,OPENSSL_ALGO_SHA256);$failed=false;try{$v->verify($bad,$badSig,'5.3.1');}catch(UpdateException $e){$failed=$e->errorCode()==='UPDATE_MANIFEST_INVALID';}um_ok($failed,'delete/package path overlap rejected');

@unlink($tmp);echo "Updater signed-manifest checks passed.\n";
