<?php
require_once '../includes/auth.php';
require_once '../includes/security.php';
require_once '../includes/database.php';
require_once '../includes/admin_helpers.php';
$auth = new Auth();
if (!$auth->isAdminLoggedIn()) { header('Location: login.php'); exit; }
$db = Database::getInstance();
$rows = [];
if (AdminHelpers::tableExists('audit_trail')) {
    $rows = $db->query("SELECT a.*, u.username FROM audit_trail a LEFT JOIN admin_users u ON a.admin_id = u.id ORDER BY a.created_at DESC LIMIT 1000")->fetchAll();
}
?>
<!doctype html><html lang="en" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Audit Trail · Licora</title><link rel="icon" href="assets/brand/favicon/favicon.ico"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"><link rel="stylesheet" href="assets/css/admin-ui.css"></head><body class="admin-ui"><?php include 'includes/navbar.php'; ?><div class="container-fluid admin-shell"><div class="page-hero"><h2><i class="bi bi-journal-text"></i> Audit Trail</h2></div><?php if(!AdminHelpers::tableExists('audit_trail')): ?><div class="alert alert-warning">Run <code>migration-v4.sql</code> to enable the full audit trail.</div><?php endif; ?><section class="card ui-table-panel"><div class="card-header"><h5 class="mb-0">Recent Changes</h5></div><div class="card-body py-2"><div class="ui-table-toolbar"><div class="ui-table-toolbar-main"><input type="search" class="form-control" placeholder="Search audit trail" data-ui-table-search="audit-table"></div><div class="ui-table-toolbar-actions"><select class="form-select" data-ui-table-size="audit-table"><option value="10">10 / page</option><option value="25">25 / page</option><option value="50">50 / page</option></select></div></div></div><div class="table-responsive ui-scrollbar"><table class="table table-hover align-middle" data-ui-paginate="true" data-ui-page-size="10" id="audit-table"><thead><tr><th>Time</th><th>Admin</th><th>Entity</th><th>Action</th><th>Details</th><th>IP</th></tr></thead><tbody><?php foreach($rows as $r): $search=trim(($r['created_at']??'').' '.($r['username']??'System').' '.($r['entity_type']??'').' '.($r['entity_id']??'').' '.($r['action']??'').' '.($r['details']??'').' '.($r['ip_address']??'')); ?><tr data-ui-search="<?php echo Security::escape($search); ?>"><td><?php echo Security::escape($r['created_at']); ?></td><td><?php echo Security::escape($r['username'] ?: 'System'); ?></td><td><?php echo Security::escape($r['entity_type']); ?> #<?php echo Security::escape($r['entity_id']); ?></td><td><span class="badge bg-primary"><?php echo Security::escape($r['action']); ?></span></td><td><?php echo Security::escape($r['details']); ?></td><td><?php echo Security::escape($r['ip_address']); ?></td></tr><?php endforeach; ?></tbody></table></div><div class="ui-table-footer"><span data-ui-count-for="audit-table"></span><nav><ul class="pagination mb-0" data-ui-pager-for="audit-table"></ul></nav></div></section></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script><script src="assets/js/admin-ui.js"></script></body></html>