<?php
require_once '../includes/auth.php';
require_once '../includes/security.php';
require_once '../includes/admin_helpers.php';
require_once '../includes/updater/bootstrap.php';
$auth=new Auth();if(!$auth->isAdminLoggedIn()){header('Location: login.php');exit;}if(!AdminHelpers::canDelete()){http_response_code(403);die('Super Admin permission is required for application updates.');}
$csrf=Security::generateCSRFToken();$initialError='';$update=['current_version'=>APP_VERSION,'latest'=>null,'update_available'=>false,'last_checked_at'=>null];$active=null;$history=[];
try{[$updater]=licora_updater_services();$update=$updater->checkForUpdates(false);$active=$updater->active();$history=$updater->history(20);}catch(Throwable $e){$initialError=$e instanceof UpdateException?$e->getMessage():'Updater initialization failed. Review server logs.';error_log('Updates page init: '.$e->getMessage());}
function updater_e($v){return Security::escape((string)$v);}function updater_status_class($status){return $status==='success'?'success':($status==='rolled_back'?'warning':(in_array($status,['failed'],true)?'danger':''));}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?php echo updater_e($csrf); ?>"><title>Updates - Licora</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"><link rel="stylesheet" href="assets/css/admin-ui.css"><link rel="stylesheet" href="assets/css/vibtools/vibtools-theme.css"><link rel="stylesheet" href="assets/css/licora-updater.css"></head>
<body class="admin-ui"><?php include 'includes/navbar.php'; ?>
<div class="container-fluid admin-shell"><section class="licora-updater-shell" id="licora-updater-app">
<header class="licora-updater-head"><div><p class="licora-updater-kicker">Secure Update Center</p><h1 class="licora-updater-title">Licora Application Updates</h1><p class="licora-updater-subtitle">Signed GitHub releases, staged validation, resumable installation, migration tracking, rollback protection, and live VibTools deployment logs.</p></div><div class="licora-updater-actions"><button class="vib-button" type="button" id="update-check-button"><i class="bi bi-arrow-repeat"></i> Check for Updates</button><button class="vib-button" type="button" id="update-open-logs" <?php echo $active?'':'hidden'; ?>><i class="bi bi-terminal"></i> Live Logs</button></div></header>
<div class="licora-updater-body">
<?php if($initialError!==''):?><div class="licora-inline-error" id="updater-page-error"><?php echo updater_e($initialError);?></div><?php else:?><div class="licora-inline-error" id="updater-page-error" hidden></div><?php endif;?>
<div class="licora-updater-grid">
<section class="licora-updater-card"><h2>Current Installation</h2><p>Runtime and updater readiness for this deployment.</p><div class="licora-updater-metrics"><div class="licora-updater-metric"><span>Current Version</span><strong id="current-version"><?php echo updater_e(APP_VERSION);?></strong></div><div class="licora-updater-metric"><span>Update Channel</span><strong>Stable</strong></div><div class="licora-updater-metric"><span>Update System</span><strong>Signed / Resumable</strong></div><div class="licora-updater-metric"><span>Last Checked</span><strong id="last-checked"><?php echo !empty($update['last_checked_at'])?updater_e(date('Y-m-d H:i:s',(int)$update['last_checked_at'])):'Not yet';?></strong></div></div></section>
<section class="licora-updater-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><h2>Latest Stable Release</h2><p>Only the locked official GitHub repository is accepted.</p></div><span class="vib-badge <?php echo !empty($update['update_available'])?'vib-badge-success':'';?>" id="update-availability-badge"><?php echo !empty($update['update_available'])?'Update available':'Up to date';?></span></div><div class="licora-release-box"><div class="licora-release-line"><span>Version</span><strong id="latest-version"><?php echo updater_e($update['latest']['version']??'Unavailable');?></strong></div><div class="licora-release-line"><span>Published</span><strong id="latest-published"><?php echo updater_e($update['latest']['published_at']??'—');?></strong></div></div><pre class="licora-release-notes" id="release-notes"><?php echo updater_e($update['latest']['body']??'No release metadata cached yet.');?></pre><div class="licora-updater-actions" style="margin-top:10px"><button class="vib-button" type="button" id="update-preflight-button" <?php echo empty($update['update_available'])?'disabled':'';?>>Run Preflight</button><button class="vib-button vib-button-primary" type="button" id="update-install-button" disabled>Install Update</button></div></section>
</div>
<section class="licora-updater-card"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px"><div><h2>Preflight & Installation State</h2><p>Installation remains disabled until the signed manifest and every mandatory server check pass.</p></div><span class="vib-badge" id="preflight-summary">Not run</span></div><div class="licora-preflight" id="preflight-results"><div class="licora-inline-info">Run Preflight to verify signature, PHP/extensions, storage, source permissions, disk space, and updater compatibility.</div></div><div id="active-job-panel" <?php echo $active?'':'hidden';?> style="margin-top:12px"><div class="licora-release-line"><span>Active Job</span><strong id="active-job-id"><?php echo updater_e($active['job_uuid']??'');?></strong></div><div class="licora-job-progress"><span id="active-job-progress" style="width:<?php echo (int)($active['progress']??0);?>%"></span></div><div class="licora-job-meta"><span id="active-job-stage"><?php echo updater_e($active['stage']??'');?></span><span id="active-job-percent"><?php echo (int)($active['progress']??0);?>%</span></div></div></section>
<section class="licora-updater-card"><h2>Update History</h2><p>Persistent update/rollback jobs and retained diagnostics.</p><div style="overflow:auto"><table class="licora-update-history"><thead><tr><th>Version</th><th>Status</th><th>Started</th><th>Finished</th><th>Actions</th></tr></thead><tbody id="update-history-body"><?php if(!$history):?><tr><td colspan="5">No updater jobs yet. v5.3.0 is the bootstrap updater release.</td></tr><?php else:foreach($history as $row):?><tr data-history-job="<?php echo updater_e($row['job_uuid']);?>"><td><?php echo updater_e($row['from_version'].' → '.$row['target_version']);?></td><td><span class="vib-badge vib-badge-<?php echo updater_status_class($row['status']);?>"><?php echo updater_e($row['status']);?></span></td><td><?php echo updater_e($row['created_at']);?></td><td><?php echo updater_e($row['finished_at']??'—');?></td><td><a class="vib-button" href="ajax/update-diagnostics.php?job=<?php echo urlencode($row['job_uuid']);?>">Diagnostics</a><?php if($row['status']==='success'&&APP_VERSION===$row['target_version']):?> <button class="vib-button vib-button-danger" type="button" data-update-rollback="<?php echo updater_e($row['job_uuid']);?>">Rollback</button><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
</div></section></div>
<div class="vib-modal-backdrop" id="licora-update-log-modal" role="dialog" aria-modal="true" aria-labelledby="licora-update-log-title" hidden><div class="vib-modal-dialog"><header class="vib-log-modal-header"><div class="vib-log-modal-title-row"><h2 class="vib-log-modal-title" id="licora-update-log-title">Licora Update</h2><button class="vib-log-close" type="button" data-log-close aria-label="Close update logs">×</button></div><div class="vib-log-modal-subbar"><div class="vib-log-modal-meta"><span id="update-log-description">Verified updater event stream</span><span class="vib-badge" id="update-log-count">0 / 0 lines</span></div><div class="vib-log-modal-controls"><button class="vib-button" type="button" id="update-copy-logs">Copy Logs</button><a class="vib-button" id="update-download-diagnostics" href="#">Download Diagnostics</a></div></div></header><div class="vib-log-tools"><label class="vib-log-search"><span class="visually-hidden">Search logs</span><svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="7" cy="7" r="4.2" fill="none" stroke="currentColor" stroke-width="1.7"></circle><path d="m10.2 10.2 3 3" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"></path></svg><input class="vib-input" type="search" id="update-log-search" placeholder="Search logs..."></label><select class="vib-select vib-log-filter" id="update-log-filter"><option value="">All levels</option><option value="info">Info</option><option value="debug">Debug</option><option value="warning">Warning</option><option value="success">Success</option><option value="error">Error</option></select><label class="vib-log-pin"><input type="checkbox" id="update-log-pin" checked> Pin to bottom</label></div><div class="vib-log-viewport" id="update-log-viewport" tabindex="0" aria-label="Licora update terminal log stream"><div class="vib-log-empty" id="update-log-empty">Waiting for updater events…</div></div><footer class="vib-log-footer"><span id="update-log-stage">Stage: idle</span><span>Closing this window does not cancel the update · Esc to close</span></footer></div></div>
<script>window.LicoraUpdaterInitial=<?php echo json_encode(['update'=>$update,'active_job'=>$active,'history'=>$history],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_SLASHES);?>;</script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script><script src="assets/js/admin-ui.js"></script><script src="assets/js/licora-updater.js"></script></body></html>
